# -*- coding: utf-8 -*-
"""unloxproject1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12blbP5-4NrMxnVxC53zZ-3WrB_IGhSpM
"""

# Define a function as attendance_checker
def attendance_checker():

    # Ask the user to enter the total number of classes
    total_classes = int(input("Enter total number of classes: "))

    # Ask the user to enter the number of classes attended
    attended_classes = int(input("Enter number of classes attended: "))

    # Calculate attendance percentage
    percentage = (attended_classes / total_classes) * 100

    # Print the attendance percentage
    print("Attendance Percentage:", percentage)

    #If attendance is more than 90%
    if percentage >= 90:
         # If condition is true, print excellent! message
        print("Excellent! You are fully eligible for the exam.")
    # If attendance is more than 75%
    if percentage >= 75:
        # If condition is true, print eligible message
        print("You are eligible for exam,Try to attend more classes")
        # If attendance is between 50% and 74%
    elif percentage >= 50:
       # If condition is true, print warning! message
        print("Warning! Attendance is low. You may not be allowed in some cases.")
        # If attendance is below 50%
    elif percentage <=50:
        # If condition is false, print not eligible message
        print("You are not eligible for exam")

# Call the function to run the program
attendance_checker()